openapi: 3.0.3
info:
  title: API Datos
  description: API para enviar y obtener datos
  version: 1.0.0
servers:
  - url: https://localhost:8080
paths:
  /datos:
    get:
      summary: Devuelve todos los datos almacenados
      operationId: getDatos2
      responses:
        "200":
          description: Lista de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dato'
        "500":
          description: Error interno del servidor
    post:
      summary: Envía un dato para almacenarlo
      operationId: postDato
      requestBody:
        description: Dato a almacenar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewDato'
      responses:
        "201":
          description: Dato almacenado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dato'
        "400":
          description: Datos inválidos (por ejemplo, si no se envía un número)
        "500":
          description: Error interno del servidor
components:
  schemas:
    Dato:
      type: object
      properties:
        id:
          type: integer
          description: Identificador del dato
        value:
          type: number
          description: El valor del dato
      example:
        id: 1
        value: 42

    NewDato:
      type: object
      properties:
        value:
          type: number
          description: El dato a almacenar
      required:
        - value
      example:
        value: 42
