services:
  php:
    image: haoxux/biometria-php:v2
    container_name: php-backend
    volumes:
      - ./backend:/var/www/html  # Mapea los archivos PHP al contenedor
      - ./db:/var/www/db  # Mapea los archivos de base de datos al contenedor
      - ./controllers:/var/www/controllers  # Mapea los archivos de controladores al contenedor
      - ./.env:/var/www/.env  # Mapea el archivo .env al contenedor
      - ./logs:/var/www/logs  # Mapea la carpeta de logs al contenedor
      - ./api:/var/www/api  # Mapea la carpeta de api al contenedor
      - ./init.sh:/usr/local/bin/init.sh  # Mapea el script de inicialización
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: ["/bin/bash", "/usr/local/bin/init.sh"]  # Ejecuta el script de inicialización

  db:
    image: haoxux/biometria-sql:v0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Usar la ruta correcta para el archivo init.sql

volumes:
  db_data:
