services:
  php:
    image: haoxux/biometria-php:v2
    container_name: php-backend
    volumes:
      - ./backend:/var/www/html/backend          #Mapeo la carpeta de backend
      - ./frontend:/var/www/html/frontend        #Mapeo la carpeta de frontend
      - ./db:/var/www/html/db                    #Mapeo la carpeta de db
      - ./logs:/var/www/html/logs                #Mapeo la carpeta de logs
      - ./.env:/var/www/html/.env                #Mapeo lel archivo .env
      - ./init.sh:/usr/local/bin/init.sh         #Mapeo el archivo de permiso
    ports:
      - "8080:80"  # Sigue exponiendo el puerto 8080 para acceso externo
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: ["/bin/bash", "/usr/local/bin/init.sh"]

  db:
    image: haoxux/biometria-sql:v0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

