openapi: 3.0.3
info:
  title: API ECOBREEZE DATOS
  description: API para obtener las mediciones de un usuario.
  version: 2.0.0
servers:
  - url: http://localhost:8080/api/api_datos.yaml
    description: 'Servidor de desarrollo'

paths:
  /obtener_mediciones_usuario:
    post:
      summary: "Obtener mediciones de un usuario específico"
      description: "Este endpoint obtiene las mediciones asociadas a un usuario, a partir de su ID."
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario_id:
                  type: integer
                  description: "ID único del usuario para obtener las mediciones."
                  example: 123
      responses:
        '200':
          description: "Mediciones obtenidas exitosamente"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  mediciones:
                    type: array
                    items:
                      type: object
                      properties:
                        fecha:
                          type: string
                          format: date
                          example: "2024-11-19"
                        valor:
                          type: number
                          format: float
                          example: 98.6
        '400':
          description: "Solicitud incorrecta, falta el ID del usuario"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "El ID del usuario es obligatorio."
        '404':
          description: "No se encontraron mediciones para el usuario"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "No se encontraron mediciones para este usuario."
        '500':
          description: "Error interno en el servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Error al obtener las mediciones."

components:
  schemas:
    Mediciones:
      type: object
      properties:
        fecha:
          type: string
          format: date
          description: "Fecha de la medición"
        valor:
          type: number
          format: float
          description: "Valor de la medición"
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: "Mensaje de error"