openapi: 3.0.3
info:
  title: API USUARIO
  description: API para lectura, escritura, eliminación y edición de datos de usuarios y sensores.
  version: 1.0.0

servers:
  - url: http://localhost/ECOBREEZE/usuarios
    description: 'Servidor de desarrollo'

paths:
  /leer:
    get:
      summary: Obtiene los datos de usuarios filtrados por diferentes criterios
      tags:
        - Usuarios
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: false
          description: ID numérico del usuario (opcional)
        - in: query
          name: nombre
          schema:
            type: string
          required: false
          description: Nombre del usuario (opcional)
        - in: query
          name: apellidos
          schema:
            type: string
          required: false
          description: Apellidos del usuario (opcional)
        - in: query
          name: email
          schema:
            type: string
          required: false
          description: Correo electrónico del usuario (opcional)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
        '404':
          description: No se encontró el usuario.
        '5XX':
          description: Error del servidor.

  /registrar:
    post:
      summary: Registra un nuevo usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                apellidos:
                  type: string
                email:
                  type: string
                contrasena:
                  type: string
                rol_rolid:
                  type: integer
              required:
                - nombre
                - apellidos
                - email
                - contrasena
      responses:
        '200':
          description: Usuario registrado con éxito.
        '400':
          description: Error de validación, campos obligatorios no proporcionados o email en uso.
        '5XX':
          description: Error del servidor.

  /iniciar_sesion:
    post:
      summary: Inicia sesión de un usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                contrasena:
                  type: string
              required:
                - email
                - contrasena
      responses:
        '200':
          description: Inicio de sesión exitoso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  usuario_id:
                    type: integer
                  usuario:
                    type: object
                    properties:
                      ID:
                        type: integer
                      Nombre:
                        type: string
                      Rol:
                        type: string
        '401':
          description: Credenciales inválidas.
        '5XX':
          description: Error del servidor.

  /editar:
    put:
      summary: Modifica los datos de un usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                nombre:
                  type: string
                apellidos:
                  type: string
                email:
                  type: string
                contrasenaHash:
                  type: string
                tfa_secret:
                  type: string
                rol_rolid:
                  type: integer
              required:
                - id
      responses:
        '200':
          description: OK
        '404':
          description: No se encontró el usuario.
        '5XX':
          description: Error del servidor.

  /borrar/{id}:
    delete:
      summary: Elimina un usuario
      tags:
        - Usuarios
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID numérico del usuario
      responses:
        '200':
          description: OK
        '404':
          description: No se encontró el usuario.
        '5XX':
          description: Error del servidor.

  /insertar_sensor:
    post:
      summary: Inserta un nuevo sensor
      tags:
        - Sensores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario_id:
                  type: integer
                mac:
                  type: string
              required:
                - usuario_id
                - mac
      responses:
        '200':
          description: Sensor insertado con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Usuario ID y MAC son obligatorios.
        '5XX':
          description: Error del servidor.

  /cambiar_contrasena:
    put:
      summary: Cambia la contraseña de un usuario
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: ID del usuario que desea cambiar la contraseña
                contrasena_actual:
                  type: string
                  description: Contraseña actual del usuario para verificación
                nueva_contrasena:
                  type: string
                  description: Nueva contraseña que se desea establecer
              required:
                - id
                - contrasena_actual
                - nueva_contrasena
      responses:
        '200':
          description: Contraseña cambiada con éxito.
        '400':
          description: ID de usuario, contraseña actual y nueva contraseña son obligatorios.
        '401':
          description: Contraseña actual incorrecta.
        '404':
          description: No se encontró el usuario.
        '5XX':
          description: Error del servidor.

  /obtener_datos_usuario_id:
    get:
      summary: Obtiene los datos básicos de un usuario por ID
      tags:
        - Usuarios
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          required: true
          description: ID del usuario
      responses:
        '200':
          description: Datos del usuario obtenidos con éxito.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  usuario:
                    $ref: '#/components/schemas/Usuario'
        '404':
          description: No se encontró el usuario.
        '400':
          description: ID de usuario es obligatorio.
        '5XX':
          description: Error del servidor.

  /verificar_correo:
    post:
      summary: Verifica el correo de un usuario mediante correo electrónico y token
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Correo electrónico del usuario
                token_verificacion:
                  type: string
                  description: Token de verificación enviado al correo del usuario
              required:
                - email
                - token_verificacion
      responses:
        '200':
          description: Verificación exitosa.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indica si la verificación fue exitosa
                  message:
                    type: string
                    description: Mensaje de confirmación
        '400':
          description: Token de verificación inválido, expirado o correo incorrecto.
        '404':
          description: Usuario no encontrado.
        '5XX':
          description: Error del servidor.

  /recuperar_contrasena:
    post:
      summary: Recupera la contraseña de un usuario mediante correo electrónico
      tags:
        - Usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Correo electrónico del usuario para enviar el token de recuperación
              required:
                - email
      responses:
        '200':
          description: Se ha enviado un token de recuperación al correo electrónico.
        '400':
          description: Correo electrónico no encontrado o inválido.
        '5XX':
          description: Error del servidor.

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          description: ID del usuario
        nombre:
          type: string
          description: Nombre del usuario
        apellidos:
          type: string
          description: Apellidos del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        contrasenaHash:
          type: string
          description: Contraseña del usuario (almacenada como hash)
        tfa_secret:
          type: string
          description: Secreto para la autenticación de dos factores
        rol_rolid:
          type: integer
          description: ID del rol del usuario
        verificado:
          type: boolean
          description: Estado de verificación del correo
      required:
        - id
        - nombre
        - email
